### ISSUE TITLE
Weight change data, AtomicBEnabled / CBBEEnabled never set

### ISSUE THREAD

**Issue by qwaqrm** [Carreau00/FVSE-papyrus#1]
https://github.com/Carreau00/FVSE-papyrus/blob/ec8fbf08ec4fdeeefc89cad0b7ce390bf7794538/FV_WeightChangeScript.psc#L514

I don't know if the commenting was intentional, maybe they should be removed?
This causes the section to calculate the slider to always return 0/0 so the thicc slider UI doesn't work.

**Comment by Carreau00** [comment]
That was an older method of determining slider sets.  I moved towards a single int rather than multiple bools.  The issue that's causing the UI to show 0 occurs in the function UpdateThiccnessMeter() on line 2171.  I neglected to update the checks there to the new global INT and they were still conditionalizing on the older struct stored bools.  That was corrected in 3.0.2.  And then there was an additional issue with sliders weren't updated for min to equal thin and max to equal thicc.  That's being corrected in 3.0.3
